Repository DoubleML/doubleml-for-py, pull requests merged in 2022-11, with the labels that each got.

#159 Store estimated models for nuisance parameters
  doubleml/_utils.py
  doubleml/double_ml.py
  doubleml/double_ml_iivm.py
  doubleml/double_ml_irm.py
  doubleml/double_ml_pliv.py
  doubleml/double_ml_plr.py
  doubleml/tests/test_cv_predict.py
  doubleml/tests/test_doubleml_exceptions.py
  doubleml/tests/test_doubleml_return_types.py
Labels: enhancement

#157 Adding CATE and GATE estimation
  .gitignore
  doubleml/__init__.py
  doubleml/double_ml_blp.py
  doubleml/double_ml_irm.py
  doubleml/tests/_utils_blp_manual.py
  doubleml/tests/test_blp.py
  doubleml/tests/test_doubleml_exceptions.py
  doubleml/tests/test_irm.py
Labels: new feature

#178 increment actions versions
  .github/workflows/deploy_pkg.yml
  .github/workflows/pytest.yml
Labels: continuous integration
