Repository DoubleML/doubleml-for-py, pull requests merged in 2025-05, with the labels that each got.

#319 Update workflows
  .github/workflows/pytest.yml
Labels: continuous integration

#318 Methods for confidence sets for IV models that are robust to weak instruments
  doubleml/irm/iivm.py
  doubleml/irm/tests/test_iivm_unif_confset.py
  doubleml/utils/_estimation.py
  doubleml/utils/tests/test_quadratic_inequality.py
Labels: new feature

#324 Update Variance aggregation
  doubleml/double_ml.py
  doubleml/double_ml_framework.py
  doubleml/plm/tests/_utils_plr_manual.py
  doubleml/tests/_utils.py
  doubleml/tests/_utils_doubleml_sensitivity_manual.py
  doubleml/tests/test_framework_sensitivity.py
  doubleml/tests/test_multiway_cluster.py
  doubleml/utils/_estimation.py
  doubleml/utils/tests/test_var_est_and_aggregation.py
Labels: refactoring

#321 Add CITATION.cff
  CITATION.cff
  README.md
Labels: documentation

#327 Add python 3.13 to build workflow
  .github/workflows/pytest.yml
Labels: continuous integration
